logging:
  level:
    ru.yandex.practicum.infra.configserver: INFO
    org:
      springframework: INFO

spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          searchLocations:
            - classpath:config/telemetry/{application}
            - classpath:config/infra/{application}

server:
  port: 8888


eureka:
  client:
    serviceUrl:

      #      зона обнаружения серсиса-реестра
      defaultZone: http://localhost:8761/eureka/

  #       не регистрироваться в сервисе-реестре
  #      registerWithEureka: false

  #  instance:

  #    управление адресом этого сервиса
  #    preferIpAddress: false
  #    hostname: external.host
  #    hostname: localhost

  #    дополнительные свойства сервиса
  #    metadataMap:
  #      customParam: customValue
  #      anotherParam: anotherValue
