version: "3"
services:
   # Eureka Server
  discovery-server:
    build:
      context: ./infra/discovery-server
      dockerfile: Dockerfile
#    image: discovery-server
    container_name: eureka-server
    ports:
      - "8761:8761"  # UI Eureka доступен на хосте
#    volumes:
#      - ./eureka-server/target/eureka-server.jar:/app.jar
#    command: java -jar /app.jar
#    environment:
#      - SPRING_PROFILES_ACTIVE=docker
#      - CONFIG_SERVER_HOST=config-server
    healthcheck:
      start_period: 10s
      test: ["CMD-SHELL", "curl -f http://localhost:8761"]
      interval: 30s
      timeout: 10s
      retries: 10
    networks:
      - sht

  # Config Server
  config-server:
    build:
      context: ./infra/config-server
      dockerfile: Dockerfile
#    image: config-server
    container_name: config-server
    ports:
      - "8888:8888"  # пробрасываем на хост для отладки
#    volumes:
#      - ./config-server/target/config-server.jar:/app.jar
#    command: java -jar /app.jar
    environment:
      - eureka.instance.hostname=discovery-server
#      - SPRING_PROFILES_ACTIVE=docker
    healthcheck:
      start_period: 10s
      test: ["CMD-SHELL", "curl -f http://localhost:8888/actuator/info"]
      interval: 30s
      timeout: 10s
      retries: 10
    depends_on:
      discovery-server:
        condition: service_healthy
    networks:
      - sht

  # postgres
  postgres-psht:
    image: postgres:16.1
    container_name: postgres-psht
    ports:
      - "5432:5432"
    volumes:
#      - ./create_dbs.sh:/pg-init-scripts/create_dbs.sh
#      - ./pg-init-scripts:/docker-entrypoint-initdb.d

      - ./create_dbs.sh:/docker-entrypoint-initdb.d/create_dbs.sh
    environment:
      - POSTGRES_PASSWORD=password
      - PGUSER=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_MULTIPLE_DATABASES=commerce_warehouse, commerce_shopping_store,
        commerce_shopping_cart, commerce_payment, commerce_order, commerce_delivery

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -q"]
      timeout: 10s
      interval: 5s
      retries: 5
    networks:
      - sht

  # gateway
  gateway:
    build:
      context: ./infra/gateway-server
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    environment:
      - eureka.instance.hostname=discovery-server
    restart: on-failure
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
    networks:
      - sht

  # delivery Service (динамический порт)
  delivery:
    build:
      context: ./commerce/delivery
      dockerfile: Dockerfile
    container_name: delivery
    environment:
      - eureka.instance.hostname=discovery-server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-psht:5432/commerce_warehouse
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    restart: on-failure
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres-psht:
        condition: service_healthy
    networks:
      - sht

  # Order Service (динамический порт)
  order:
    build:
      context: ./commerce/order
      dockerfile: Dockerfile
    container_name: order
    environment:
      - eureka.instance.hostname=discovery-server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-psht:5432/commerce_warehouse
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    restart: on-failure
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres-psht:
        condition: service_healthy
    networks:
      - sht

  # payment Service (динамический порт)
  payment:
    build:
      context: ./commerce/payment
      dockerfile: Dockerfile
    container_name: payment
    environment:
      - eureka.instance.hostname=discovery-server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-psht:5432/commerce_warehouse
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    restart: on-failure
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres-psht:
        condition: service_healthy
    networks:
      - sht

  # shoping-cart Service (динамический порт)
  shopping-cart:
    build:
      context: ./commerce/shopping-cart
      dockerfile: Dockerfile
    container_name: shopping-cart
    environment:
      - eureka.instance.hostname=discovery-server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-psht:5432/commerce_warehouse
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    restart: on-failure
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres-psht:
        condition: service_healthy
    networks:
      - sht

  # shoping-store Service (динамический порт)
  shopping-store:
    build:
      context: ./commerce/shopping-store
      dockerfile: Dockerfile
    container_name: shopping-store
    environment:
      - eureka.instance.hostname=discovery-server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-psht:5432/commerce_warehouse
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    restart: on-failure
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres-psht:
        condition: service_healthy
    networks:
      - sht

  # Warehouse Service (динамический порт)
  warehouse:
    build:
      context: ./commerce/warehouse
      dockerfile: Dockerfile
    container_name: warehouse
    environment:
      - eureka.instance.hostname=discovery-server
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-psht:5432/commerce_warehouse
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=password
    restart: on-failure
    depends_on:
      discovery-server:
        condition: service_healthy
      config-server:
        condition: service_healthy
      postgres-psht:
        condition: service_healthy
    networks:
      - sht

networks:
  sht:
    driver: bridge