grpc:
  client:
    hub-router:
      address: 'static://localhost:59090'
      enableKeepAlive: true
      keepAliveWithoutCalls: true
      negotiationType: plaintext

logging:
  level:
    ru.practicum: trace
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE

spring:
 kafka:
   bootstrap-servers: localhost:9092
   topics:
    telemetry-hubs-topics: "telemetry.hubs.v1"
    telemetry-sensors-topics: "telemetry.sensors.v1"
    telemetry-snapshots-topics: "telemetry.snapshots.v1"
   consumer:
    client-id: "SomeConsumer"
    group-id: "some.group.id-"
    auto-offset-reset: "earliest"
    auto-commit: false
    key-deserializer: "org.apache.kafka.common.serialization.StringDeserializer"
    value-deserializer: "ru.yandex.practicum.kafka.deserializer.SensorEventDeserializer"
    max-poll-record-config: 100
    fetch-max-bytes-config: 3072000
    max-partition-fetch-bytes-config: 307200

 datasource:
   url: jdbc:postgresql://localhost:6432/sht
   driver-class-name: org.postgresql.Driver
   username: sht
   password: sht
 sql:
   init:
    mode: always
 jpa:
   #    show-sql: true
   hibernate:
    ddl-auto: none
   properties:
    hibernate:
#        format_sql: true
#        time_zone: UTC
#        default_schema: public
